### PR TITLE
Handle factory

### LINKED ISSUE #15: Not working with factory ?
We have a factory that creates a guzzle client, this factory returns the guzzle client with a handler created given some arguments.

The service looks like this:
```yaml

    admin.microservice.client:
        class: GuzzleHttp\Client
        factory: [\Agriconomie\Microservice\ClientFactory, create]
        arguments:
            $debug: '%kernel.debug%'
            $logger: '@monolog.logger.internal_api'
```

And the factory:
```php
    /**
     * @param bool $debug
     * @param LoggerInterface|null $logger
     */
    public static function create(bool $debug, ?LoggerInterface $logger) {
        $handlerStack = HandlerStack::create();
        $client = new \GuzzleHttp\Client([
            'handler' => $handlerStack
        ]);
        if (null !== $logger) {
            $handlerStack->push(Middleware::log($logger, new MessageFormatter(MessageFormatter::SHORT), LogLevel::INFO));
            if ($debug) {
                $handlerStack->push(Middleware::log($logger, new MessageFormatter(MessageFormatter::DEBUG), LogLevel::DEBUG));
            }
        }
        return $client;
    }
```

I integrated the opentracing guzzle bundle, it breaks here i think:
https://github.com/auxmoney/OpentracingBundle-Guzzle/blob/ced155c3335adf4341e22365470f5aa302dc16ef/DependencyInjection/GuzzleHandlerStackCompilerPass.php#L24-L30

probably because of this:
https://github.com/auxmoney/OpentracingBundle-Guzzle/blob/ced155c3335adf4341e22365470f5aa302dc16ef/DependencyInjection/GuzzleHandlerStackCompilerPass.php#L58-L70

Shouldn't the `process` method take care of the factory use case ?

Thanks.

### PR DESCRIPTION
**Pull request by VincentLemaireAgriconomie**
fixing https://github.com/auxmoney/OpentracingBundle-Guzzle/issues/15

### CODE REVIEW

File: Decorator/GuzzleClientFactoryDecorator.php [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+use GuzzleHttp\Client;
+use GuzzleHttp\HandlerStack;
+use Symfony\Component\DependencyInjection\Reference;
+
+final class GuzzleClientFactoryDecorator
+{
+
+    private $decorated;
+
+    public function __call($method, $args)
```
Comment (cawolf) [inline Decorator/GuzzleClientFactoryDecorator.php]: Does this also intercept other methods like `setDependency()`? Can this be an issue for setter injection?

Can't we get the original information of the factory (in the compiler pass, from the definition) and pass it in here, so that only this method is intercepted by `__call`?

File: Decorator/GuzzleClientFactoryDecorator.php [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+    {
+        if (is_callable($this->decorated, $method)) {
+
+            /** @var Client $client */
+            $client = call_user_func_array(array($this->decorated, $method), $args);
+
+            $handler = $client->getConfig("handler");
+            if (is_object($handler) && is_a($handler, HandlerStack::class)) {
```
Comment (cawolf) [inline Decorator/GuzzleClientFactoryDecorator.php]: `is_a` is deprecated in favor of `instanceof`

File: Decorator/GuzzleClientFactoryDecorator.php [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+                $handler->push(new Reference(GuzzleRequestSpanning::class));
+                $handler->push(new Reference(GuzzleTracingHeaderInjection::class));
```
Comment (cawolf) [inline Decorator/GuzzleClientFactoryDecorator.php]: Here, you need to push the actual services instead of references, because you are outside of the container building process. So you need to inject these services to this decorator and then just pass them into the `$handler` with `push()`.

File: Decorator/GuzzleClientFactoryDecorator.php [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+            }
+
+            return $client;
+
+        }
+        throw new Exception(
```
Comment (cawolf) [inline Decorator/GuzzleClientFactoryDecorator.php]: This is still WIP? Because right now, it will always throw this exception.

File: Decorator/GuzzleClientFactoryDecorator.php (hunk 1 above)
Comment (cawolf) [reply Decorator/GuzzleClientFactoryDecorator.php]: Oh, scrolling down revealed, that you already have that information: its `callable $factory` in `addMiddlewareToClientFactory()`.

**Review by cawolf — CHANGES_REQUESTED** [review]

File: Decorator/GuzzleClientFactoryDecorator.php (hunk 4 above)
Comment (VincentLemaireAgriconomie) [reply Decorator/GuzzleClientFactoryDecorator.php]: @cawolf yes it's an early wip to design the bones of the feature, thanks for your review :)

**Comment by VincentLemaireAgriconomie** [comment]
i'm stuck against a wall here ...
the signature of our factories is something like 
``` 
public create (bool $debug): Client {...}
```
with the code in the PR, when replacing the factory i got a symfony error `method create does not exist in GuzzleClientFactoryDecorator`

so i change the decorator with  : 
``` 
    public function __invoke()
    {
        $client = call_user_func($this->factory, func_get_args());
...
        return $client;
    }
```
but i got : `__invoke() has no argument named "$debug"`

@cawolf do you have any suggestion ?

File: Decorator/GuzzleClientFactoryDecorator.php [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+use Auxmoney\OpentracingGuzzleBundle\Middleware\GuzzleRequestSpanning;
+use Auxmoney\OpentracingGuzzleBundle\Middleware\GuzzleTracingHeaderInjection;
+use GuzzleHttp\Client;
+use GuzzleHttp\HandlerStack;
+use Symfony\Component\DependencyInjection\Reference;
+
+final class GuzzleClientFactoryDecorator
+{
+
+    public function decorate(Client $client, GuzzleRequestSpanning $spanning, GuzzleTracingHeaderInjection $injection)
```
Comment (eddycharly) [inline Decorator/GuzzleClientFactoryDecorator.php]: the method can be static

File: DependencyInjection/GuzzleHandlerStackCompilerPass.php [hunk 6]
```diff
@@ -23,13 +24,23 @@ public function process(ContainerBuilder $container): void
...
-                $this->addMiddlewareToClient($container, $definition, $clientServiceName);
+                $this->processClient($container, $definition, $clientServiceName);
             } elseif ($definition->getClass() === HandlerStack::class) {
                 $this->addUniqueMethodCallsToHandlerStack($definition);
             }
         }
     }
 
+    private function processClient(ContainerBuilder $container, Definition $definition, string $clientServiceName): void
+    {
```
Comment (eddycharly) [inline DependencyInjection/GuzzleHandlerStackCompilerPass.php:31]: No need to treat the factory case specifically, always relying on decorator should be a better option.

File: Decorator/GuzzleClientFactoryDecorator.php [hunk 7]
```diff
@@ -0,0 +1,28 @@
...
+
+    public static function decorate(
+        Client $client,
+        GuzzleRequestSpanning $spanning,
+        GuzzleTracingHeaderInjection $headerInjection
+    )
+    {
+        $handler = $client->getConfig("handler");
+        if ($handler instanceof HandlerStack) {
+            $handler->push($spanning);
```
Comment (eddycharly) [inline Decorator/GuzzleClientFactoryDecorator.php:22]: Should check for deduplication here

File: Decorator/GuzzleClientFactoryDecorator.php [hunk 8]
```diff
@@ -0,0 +1,28 @@
...
+{
+
+    public static function decorate(
+        Client $client,
+        GuzzleRequestSpanning $spanning,
+        GuzzleTracingHeaderInjection $headerInjection
+    )
+    {
+        $handler = $client->getConfig("handler");
+        if ($handler instanceof HandlerStack) {
```
Comment (eddycharly) [inline Decorator/GuzzleClientFactoryDecorator.php:21]: Why is checking `instanceof HandlerStack` needed ?

File: Decorator/GuzzleClientFactoryDecorator.php [hunk 9]
```diff
@@ -0,0 +1,28 @@
...
+
+declare(strict_types=1);
+
+namespace Auxmoney\OpentracingGuzzleBundle\Decorator;
+
+use Auxmoney\OpentracingGuzzleBundle\Middleware\GuzzleRequestSpanning;
+use Auxmoney\OpentracingGuzzleBundle\Middleware\GuzzleTracingHeaderInjection;
+use GuzzleHttp\Client;
+use GuzzleHttp\HandlerStack;
+use Symfony\Component\DependencyInjection\Reference;
```
Comment (eddycharly) [inline Decorator/GuzzleClientFactoryDecorator.php]: Import is not used

**Comment by cawolf** [comment]
Side note: currently, on PHP 7.1 / SF 3.4, with your code and this factory definition
```yaml
    admin.microservice.client:
        class: GuzzleHttp\Client
        factory: [\Agriconomie\Microservice\ClientFactory, create]
        arguments:
            $debug: '%kernel.debug%'
            $logger: '@monolog.logger.internal_api'
```
 I'm stuck at container creation time:
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 4 passed to Auxmoney\OpentracingGuzzleBundle\DependencyInjection\GuzzleHandlerStackCompilerPass::addMiddlewareToClientFactory() must be callable, array given, called in /opt/workspace/opentracing-guzzle-agriconomie/DependencyInjection/GuzzleHandlerStackCompilerPass.php on line 28 in /opt/workspace/opentracing-guzzle-agriconomie/DependencyInjection/GuzzleHandlerStackCompilerPass.php:60
Stack trace:
#0 /opt/workspace/opentracing-guzzle-agriconomie/DependencyInjection/GuzzleHandlerStackCompilerPass.php(28): Auxmoney\OpentracingGuzzleBundle\DependencyInjection\GuzzleHandlerStackCompilerPass->addMiddlewareToClientFactory(Object(Symfony\Component\DependencyInjection\ContainerBuilder), Object(Symfony\Component\DependencyInjection\Definition), 'admin.microserv...', Array)
#1 /opt/workspace/opentracing-guzzle/vendor/symfony/dependency-injection/Compiler/Compiler.php(140): Auxmoney\OpentracingGuzzleBundle\DependencyInjection\GuzzleHandler in /opt/workspace/opentracing-guzzle-agriconomie/DependencyInjection/GuzzleHandlerStackCompilerPass.php on line 60
```
Removing the `callable` type hint in `addMiddlewareToClientFactory()` solves this for me, but we need to double check that.

---

Now to your original question: it seems the symfony named parameters resolution relies on reflection (see `Symfony\Component\DependencyInjection\Compiler\ResolveNamedArgumentsPass`), and since the `GuzzleClientFactoryDecorator::__invoke()` has no arguments declared, that compiler pass will always fail.

Maybe have a look at `Auxmoney\OpentracingBundle\DependencyInjection\PSR18CompilerPass` in the core bundle, you should try to use the "decoration" feature of the symfony container. This should transparently create the original factory as is and just wrap around the new decorator factory. This way, you don't have to fiddle with the parameter bindings at all.

File: Decorator/GuzzleClientFactoryDecorator.php (hunk 8 above)
Comment (VincentLemaireAgriconomie) [reply Decorator/GuzzleClientFactoryDecorator.php:21]: i dont find strong typing, so i'm just carefull, i think it's better to not add the span than broke the code

**Comment by VincentLemaireAgriconomie** [comment]
@cawolf i removed all the callable stuff, so it's not an issue anymore

File: Decorator/GuzzleClientFactoryDecorator.php (hunk 8 above)
Comment (eddycharly) [reply Decorator/GuzzleClientFactoryDecorator.php:21]: I don't think it can be anything else than a `HandlerStack` but ok, it shouldn't hurt.
Maybe add a warning log if it's not.

File: Decorator/GuzzleClientFactoryDecorator.php [hunk 10]
```diff
@@ -0,0 +1,34 @@
...
+    ): Client {
+        $handler = $client->getConfig("handler");
+        if ($handler instanceof HandlerStack) {
+
+            // We have to remove to be sur it's unique bevause HandlerStack::findByName is private
+            $handler->remove(GuzzleHandlerStackCompilerPass::MIDDLEWARE_NAME_SPANNING);
+            $handler->remove(GuzzleHandlerStackCompilerPass::MIDDLEWARE_NAME_HEADER_INJECTION);
+
+            $handler->push($spanning, GuzzleHandlerStackCompilerPass::MIDDLEWARE_NAME_SPANNING);
+            $handler->push($headerInjection, GuzzleHandlerStackCompilerPass::MIDDLEWARE_NAME_HEADER_INJECTION);
```
Comment (VincentLemaireAgriconomie) [inline Decorator/GuzzleClientFactoryDecorator.php]: is this necessary ?

**Comment by cawolf** [comment]
Do you have any updates on this? We just stumbled upon a breaking application on our side, so we will use this feature as well.

**Comment by eddycharly** [comment]
@cawolf I will work on it this afternoon as @VincentLemaireAgriconomie is too busy these days.
I think we were close to finish, let me take a few hours and i'll get back to you.

**Comment by eddycharly** [comment]
@cawolf sorry, i had some unexpected things to do this afternoon, i will look at it tomorrow morning.

**Comment by eddycharly** [comment]
@cawolf i removed the code specific to `HandlerStack`, from my understanding it's not needed anymore.
what do you think ?

I merged all code paths into one, just decorating the `Client` service should be enough in all cases, right ?

I will begin to fix tests now.

**Comment by eddycharly** [comment]
@cawolf i began fixing the tests, it needs more work but you should get the idea of what it will look like.

let me know what you think, waiting for your feedback and i will improve the tests.

**Comment by eddycharly** [comment]
Ping @cawolf

File: Decorator/GuzzleClientFactoryDecorator.php (hunk 8 above)
Comment (cawolf) [reply Decorator/GuzzleClientFactoryDecorator.php:21]: It could be a `callable`, according to the [documentation](https://github.com/guzzle/guzzle/blob/6.5/src/Client.php#L46-L54)

**Comment by cawolf** [comment]
Besides the handler possibly being a plain `callable`, I found nothing of interest. I really don't know if someone out there uses plain functions as handlers.

**Comment by eddycharly** [comment]
Ok thanks, i will go ahead with it tomorrow, taking care of the `callable` case and reworking unit/integration tests.

**Comment by eddycharly** [comment]
Unit tests have been reworked and the `callable` case is supported.
I need to rework the integration tests, will do this in the afternoon as i don't know this part well yet.

**Comment by cawolf** [comment]
I think we need to tweak the `composer.json` of the test project to use your repository as base for installing the opentracing guzzle vendor. I will see if I can make that fix in a separate PR asap.

**Comment by eddycharly** [comment]
arf yes, i remember we already discussed this issue in a previous pr :(

**Comment by eddycharly** [comment]
@cawolf let me know when it's ready

**Comment by cawolf** [comment]
@eddycharly it is now, fixed within #19

**Comment by eddycharly** [comment]
Rebased, let's see how it goes

**Comment by eddycharly** [comment]
@cawolf looks like travis didn't start ?

**Comment by cawolf** [comment]
They are very unreliable today, some runs take more than 40 minutes

File: Decorator/GuzzleClientFactoryDecorator.php (hunk 7 above)
Comment (cawolf) [reply Decorator/GuzzleClientFactoryDecorator.php:22]: Is this comment still valid?

Comment (eddycharly) [reply Decorator/GuzzleClientFactoryDecorator.php:22]: Nope, will ask @VincentLemaireAgriconomie to mark it as resolved

**Comment by eddycharly** [comment]
@cawolf the `Auxmoney\OpentracingGuzzleBundle\Tests\Functional\NoHandlerStack` integration test fails.

From what i see, it expects the commad to fail, but it doesn't fail anymore, can you provide a bit of context for this test please ?

**Comment by cawolf** [comment]
@eddycharly this is the exact test case for handlers, that are only callables, but not `HandlerStack`s. You can see the test project [here](https://github.com/auxmoney/OpentracingBundle-Guzzle/tree/master/Tests/Functional/TestProjectFiles/existingHandler).

**Comment by eddycharly** [comment]
@cawolf it's not supposed to fail anymore i guess, right ?

**Comment by cawolf** [comment]
True, the new logic will wrap around it properly. The test should not fail anymore.

**Comment by eddycharly** [comment]
@cawolf any idea why it's failing only with sf 5 ? https://travis-ci.org/github/auxmoney/OpentracingBundle-Guzzle/jobs/682930178

**Comment by cawolf** [comment]
No, no idea. A restart helped.

**Review by cawolf — CHANGES_REQUESTED** [review]
Just a last request: can you please add a small unit test for the new decorator? After that, this PR is good to go.

**Comment by eddycharly** [comment]
Sure, i thought i did... 🤔

**Comment by eddycharly** [comment]
@cawolf I added the missing tests

**Comment by eddycharly** [comment]
Arrf, sf5 integration tests are red again :(

**Review by cawolf — APPROVED** [review]
LGTM!

**Comment by eddycharly** [comment]
:tada
